export const FETCH_COURSES = 'FETCH_COURSES';
export const ADD_COURSE = 'ADD_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const FETCH_ASSIGNMENTS = 'FETCH_ASSIGNMENTS';
export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';
