/** Admin */
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

/** Messages */
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const ADD_NEW_MESSAGE_ERROR = 'ADD_NEW_MESSAGE_ERROR';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';

/** Feed */
export const ADD_POST = 'ADD_POST';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';
export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
export const ADD_COMMENT_ON_POST = 'ADD_COMMENT_ON_POST';
export const ADD_COMMENT_ON_POST_FAIL = 'ADD_COMMENT_ON_POST_FAIL';
export const EDIT_COMMENT_ON_POST = 'EDIT_COMMENT_ON_POST';
export const EDIT_COMMENT_ON_POST_FAIL = 'EDIT_COMMENT_ON_POST_FAIL';
export const REMOVE_COMMENT_ON_POST = 'REMOVE_COMMENT_ON_POST';
export const REMOVE_COMMENT_ON_POST_FAIL = 'REMOVE_COMMENT_ON_POST_FAIL';

/** Course Catalog */
export const FETCH_CATALOG = 'FETCH_CATALOG';
export const FETCH_CATALOG_ERROR = 'FETCH_CATALOG_ERROR';

/** Courses */
export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSE = 'FETCH_COURSE';
export const ADD_COURSE = 'ADD_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';

/** Courses Assignments */
export const FETCH_ASSIGNMENTS = 'FETCH_ASSIGNMENTS';
export const ADD_ASSIGNMENT = 'ADD_ASSIGNMENT';

/** Search */
export const QUICK_SEARCH_BY_TODAY = 'QUICK_SEARCH_BY_TODAY';
export const QUICK_SEARCH_BY_TYPE = 'QUICK_SEARCH_BY_TYPE';

/** Tutor - User Availability */
export const UPDATE_AVAILABILITY = 'UPDATE_AVAILABILITY';
export const ADD_AVAILABILITY = 'ADD_AVAILABILITY';
export const REMOVE_AVAILABILITY = 'REMOVE_AVAILABILITY';

/** Flash Messages */
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
